name: ind-jobs
on: 
  push:
    paths:
      - "trigger/exp.txt"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10s
      - run: echo "Job 1 Completed"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5s
      - run: echo "Job 2 Completed"
  
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 3 Completed"