name: learn-github-actions
on: [push]
jobs:
  check-datetime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: date +"%h %d, %Y [%H:%M:%S %p]"

  word-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count words and uniqie words
        run: ./.github/scripts/word-count.sh 
        shell: bash