name: corn-schedule-action
on: 
  schedule:
    - cron: '0 12 5 * *'
    - cron: '30 12 5 * *'

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: at 6
        if: github.event.schedule == '0 12 5 * *'
        run: echo "6:00 PM 5/9/22 BDT"
      - name: every time
        run: date +"%h %d, %Y [%H:%M:%S %p]"

